version: '3'
services:
    npm-build-server:
        build:
            context: ./client
        network_mode: host
        environment:
            - API_IP
        ports:
            - "19000:19000"
            - "19001:19001"
            - "19002:19002"
        volumes:
            - ./client/app:/npm-build-server/app
        depends_on:
            - server
    server:
        build:
            context: ./server
        network_mode: host
        volumes:
            - ./server:/server
        ports:
            - "3000:3000"
    # db:
        # image: postgres
        # volumes:
            # - ./tmp/db:/var/lib/postgresql/data
