version: '3.7'
services:
    npm-build-server:
        build: .
        ports:
            - "19000:19000"
            - "19001:19001"
            - "19002:19002"
        volumes:
            - ./client/ceapp:/npm-build-server
            # - ./client/ceapp/app:/npm-build-server/app
    # db:
        # image: postgres
        # volumes:
            # - ./tmp/db:/var/lib/postgresql/data
  # web:
    # build: .
    # command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    # volumes:
        # - .:/myapp
    # ports:
        # - "3000:3000"
    # depends_on:
        # - db
